# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_sys_mb_0/system_sys_mb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb_0 || ORIG_REF_NAME==system_sys_mb_0}]

# IP: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_dlmb_0 || ORIG_REF_NAME==system_sys_dlmb_0}]

# IP: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ilmb_0 || ORIG_REF_NAME==system_sys_ilmb_0}]

# IP: bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_dlmb_cntlr_0 || ORIG_REF_NAME==system_sys_dlmb_cntlr_0}]

# IP: bd/system/ip/system_sys_ilmb_cntlr_0/system_sys_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ilmb_cntlr_0 || ORIG_REF_NAME==system_sys_ilmb_cntlr_0}]

# IP: bd/system/ip/system_sys_lmb_bram_0/system_sys_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_lmb_bram_0 || ORIG_REF_NAME==system_sys_lmb_bram_0}]

# IP: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb_debug_0 || ORIG_REF_NAME==system_sys_mb_debug_0}]

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0}]

# IP: bd/system/ip/system_sys_const_vcc_0/system_sys_const_vcc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_const_vcc_0 || ORIG_REF_NAME==system_sys_const_vcc_0}]

# IP: bd/system/ip/system_sys_const_gnd_0/system_sys_const_gnd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_const_gnd_0 || ORIG_REF_NAME==system_sys_const_gnd_0}]

# IP: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_0}]

# IP: bd/system/ip/system_sys_const_ddr3_0_0/system_sys_const_ddr3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_const_ddr3_0_0 || ORIG_REF_NAME==system_sys_const_ddr3_0_0}]

# IP: bd/system/ip/system_sys_const_ddr3_1_0/system_sys_const_ddr3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_const_ddr3_1_0 || ORIG_REF_NAME==system_sys_const_ddr3_1_0}]

# IP: bd/system/ip/system_axi_cpu_aux_interconnect_0/system_axi_cpu_aux_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_aux_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_aux_interconnect_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0}]

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1}]

# IP: bd/system/ip/system_axi_mem_interconnect_0/system_axi_mem_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_interconnect_0 || ORIG_REF_NAME==system_axi_mem_interconnect_0}]

# IP: bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2}]

# IP: bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ethernet_0 || ORIG_REF_NAME==system_axi_ethernet_0}]

# IP: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0}]

# IP: bd/system/ip/system_axi_uart_0/system_axi_uart_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0}]

# IP: bd/system/ip/system_axi_timer_0/system_axi_timer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_0 || ORIG_REF_NAME==system_axi_timer_0}]

# IP: bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_lcd_0 || ORIG_REF_NAME==system_axi_gpio_lcd_0}]

# IP: bd/system/ip/system_axi_gpio_sw_led_0/system_axi_gpio_sw_led_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_sw_led_0 || ORIG_REF_NAME==system_axi_gpio_sw_led_0}]

# IP: bd/system/ip/system_axi_intc_0/system_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0}]

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0}]

# IP: bd/system/ip/system_axi_hdmi_clkgen_0/system_axi_hdmi_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hdmi_clkgen_0 || ORIG_REF_NAME==system_axi_hdmi_clkgen_0}]

# IP: bd/system/ip/system_axi_hdmi_core_0/system_axi_hdmi_core_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0}]

# IP: bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hdmi_dma_0 || ORIG_REF_NAME==system_axi_hdmi_dma_0}]

# IP: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0}]

# IP: bd/system/ip/system_axi_spdif_tx_core_0/system_axi_spdif_tx_core_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_core_0 || ORIG_REF_NAME==system_axi_spdif_tx_core_0}]

# IP: bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_dma_0 || ORIG_REF_NAME==system_axi_spdif_tx_dma_0}]

# IP: bd/system/ip/system_axi_linear_flash_0/system_axi_linear_flash_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_linear_flash_0 || ORIG_REF_NAME==system_axi_linear_flash_0}]

# IP: bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0}]

# IP: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0}]

# IP: bd/system/ip/system_util_adc_pack_0/system_util_adc_pack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_adc_pack_0 || ORIG_REF_NAME==system_util_adc_pack_0}]

# IP: bd/system/ip/system_util_dac_unpack_0/system_util_dac_unpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_dac_unpack_0 || ORIG_REF_NAME==system_util_dac_unpack_0}]

# IP: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0}]

# IP: bd/system/ip/system_axi_fmcomms2_spi_0/system_axi_fmcomms2_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_fmcomms2_spi_0 || ORIG_REF_NAME==system_axi_fmcomms2_spi_0}]

# IP: bd/system/ip/system_axi_fmcomms2_gpio_0/system_axi_fmcomms2_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_fmcomms2_gpio_0 || ORIG_REF_NAME==system_axi_fmcomms2_gpio_0}]

# IP: bd/system/ip/system_ila_adc_0/system_ila_adc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ila_adc_0 || ORIG_REF_NAME==system_ila_adc_0}]

# IP: bd/system/ip/system_wfifo_ctl_0/system_wfifo_ctl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_wfifo_ctl_0 || ORIG_REF_NAME==system_wfifo_ctl_0}]

# IP: bd/system/ip/system_wfifo_mem_0/system_wfifo_mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_wfifo_mem_0 || ORIG_REF_NAME==system_wfifo_mem_0}]

# IP: bd/system/ip/system_wfifo_ctl_1/system_wfifo_ctl_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_wfifo_ctl_1 || ORIG_REF_NAME==system_wfifo_ctl_1}]

# IP: bd/system/ip/system_wfifo_mem_1/system_wfifo_mem_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_wfifo_mem_1 || ORIG_REF_NAME==system_wfifo_mem_1}]

# IP: bd/system/ip/system_wfifo_ctl_2/system_wfifo_ctl_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_wfifo_ctl_2 || ORIG_REF_NAME==system_wfifo_ctl_2}]

# IP: bd/system/ip/system_wfifo_mem_2/system_wfifo_mem_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_wfifo_mem_2 || ORIG_REF_NAME==system_wfifo_mem_2}]

# IP: bd/system/ip/system_wfifo_ctl_3/system_wfifo_ctl_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_wfifo_ctl_3 || ORIG_REF_NAME==system_wfifo_ctl_3}]

# IP: bd/system/ip/system_wfifo_mem_3/system_wfifo_mem_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_wfifo_mem_3 || ORIG_REF_NAME==system_wfifo_mem_3}]

# IP: bd/system/ip/system_rst_axi_ddr_cntrl_200M_0/system_rst_axi_ddr_cntrl_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_axi_ddr_cntrl_200M_0 || ORIG_REF_NAME==system_rst_axi_ddr_cntrl_200M_0}]

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}]

# IP: bd/system/ip/system_AES_AXI_0_1/system_AES_AXI_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AES_AXI_0_1 || ORIG_REF_NAME==system_AES_AXI_0_1}]

# IP: bd/system/ip/system_s05_data_fifo_0/system_s05_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s05_data_fifo_0 || ORIG_REF_NAME==system_s05_data_fifo_0}]

# IP: bd/system/ip/system_s06_data_fifo_0/system_s06_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s06_data_fifo_0 || ORIG_REF_NAME==system_s06_data_fifo_0}]

# IP: bd/system/ip/system_s07_data_fifo_0/system_s07_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s07_data_fifo_0 || ORIG_REF_NAME==system_s07_data_fifo_0}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# IP: bd/system/ip/system_s00_mmu_0/system_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_mmu_0 || ORIG_REF_NAME==system_s00_mmu_0}]

# IP: bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_0 || ORIG_REF_NAME==system_auto_us_cc_df_0}]

# IP: bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_1 || ORIG_REF_NAME==system_auto_us_cc_df_1}]

# IP: bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_2 || ORIG_REF_NAME==system_auto_us_cc_df_2}]

# IP: bd/system/ip/system_auto_us_cc_df_3/system_auto_us_cc_df_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_3 || ORIG_REF_NAME==system_auto_us_cc_df_3}]

# IP: bd/system/ip/system_auto_us_cc_df_4/system_auto_us_cc_df_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_4 || ORIG_REF_NAME==system_auto_us_cc_df_4}]

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0}]

# IP: bd/system/ip/system_auto_cc_1/system_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1 || ORIG_REF_NAME==system_auto_cc_1}]

# IP: bd/system/ip/system_auto_cc_2/system_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_2 || ORIG_REF_NAME==system_auto_cc_2}]

# IP: bd/system/ip/system_auto_us_df_0/system_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_0 || ORIG_REF_NAME==system_auto_us_df_0}]

# IP: bd/system/ip/system_auto_us_df_1/system_auto_us_df_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_1 || ORIG_REF_NAME==system_auto_us_df_1}]

# XDC: bd/system/ip/system_sys_mb_0/system_sys_mb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb_0 || ORIG_REF_NAME==system_sys_mb_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc.xdc

# XDC: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_dlmb_0 || ORIG_REF_NAME==system_sys_dlmb_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0_ooc.xdc

# XDC: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ilmb_0 || ORIG_REF_NAME==system_sys_ilmb_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0_ooc.xdc

# XDC: bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_sys_ilmb_cntlr_0/system_sys_ilmb_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_sys_lmb_bram_0/system_sys_lmb_bram_0_ooc.xdc

# XDC: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb_debug_0 || ORIG_REF_NAME==system_sys_mb_debug_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc.xdc

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0}]

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0}]

# XDC: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_0}]

# XDC: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_0}]

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc

# XDC: bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ethernet_0 || ORIG_REF_NAME==system_axi_ethernet_0}]

# XDC: bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ethernet_0 || ORIG_REF_NAME==system_axi_ethernet_0}]

# XDC: bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ethernet_0 || ORIG_REF_NAME==system_axi_ethernet_0}]

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0}]

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_timer_0/system_axi_timer_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_0 || ORIG_REF_NAME==system_axi_timer_0}]

# XDC: bd/system/ip/system_axi_timer_0/system_axi_timer_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_lcd_0 || ORIG_REF_NAME==system_axi_gpio_lcd_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_lcd_0 || ORIG_REF_NAME==system_axi_gpio_lcd_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_sw_led_0/system_axi_gpio_sw_led_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_sw_led_0/system_axi_gpio_sw_led_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_sw_led_0 || ORIG_REF_NAME==system_axi_gpio_sw_led_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_sw_led_0/system_axi_gpio_sw_led_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_sw_led_0 || ORIG_REF_NAME==system_axi_gpio_sw_led_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0_ooc.xdc

# XDC: ipshared/analog.com/axi_hdmi_tx_v1_0/008f4d65/axi_hdmi_tx_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0}]

# XDC: bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_dma_0 || ORIG_REF_NAME==system_axi_hdmi_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_dma_0 || ORIG_REF_NAME==system_axi_hdmi_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_ooc.xdc

# XDC: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_ooc.xdc

# XDC: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0}] {/inst }]/inst ]]

# XDC: ipshared/analog.com/axi_spdif_tx_v1_0/7e62f61d/axi_spdif_tx_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_core_0 || ORIG_REF_NAME==system_axi_spdif_tx_core_0}]

# XDC: bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0_ooc.xdc

# XDC: bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_dma_0 || ORIG_REF_NAME==system_axi_spdif_tx_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_dma_0 || ORIG_REF_NAME==system_axi_spdif_tx_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_linear_flash_0/system_axi_linear_flash_0_ooc.xdc

# XDC: bd/system/ip/system_axi_linear_flash_0/system_axi_linear_flash_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_linear_flash_0 || ORIG_REF_NAME==system_axi_linear_flash_0}]

# TCL: ipshared/analog.com/axi_dmac_v1_0/b096c3cf/axi_dmac_constr.tcl
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0}] {/inst }]/inst ]]

# TCL: ipshared/analog.com/axi_dmac_v1_0/b096c3cf/axi_dmac_constr.tcl
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_axi_fmcomms2_spi_0/system_axi_fmcomms2_spi_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_fmcomms2_spi_0 || ORIG_REF_NAME==system_axi_fmcomms2_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_fmcomms2_spi_0/system_axi_fmcomms2_spi_0_ooc.xdc

# XDC: bd/system/ip/system_axi_fmcomms2_spi_0/system_axi_fmcomms2_spi_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_fmcomms2_spi_0 || ORIG_REF_NAME==system_axi_fmcomms2_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_fmcomms2_spi_0/system_axi_fmcomms2_spi_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_fmcomms2_spi_0 || ORIG_REF_NAME==system_axi_fmcomms2_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_fmcomms2_gpio_0/system_axi_fmcomms2_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_axi_fmcomms2_gpio_0/system_axi_fmcomms2_gpio_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_fmcomms2_gpio_0 || ORIG_REF_NAME==system_axi_fmcomms2_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_fmcomms2_gpio_0/system_axi_fmcomms2_gpio_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_fmcomms2_gpio_0 || ORIG_REF_NAME==system_axi_fmcomms2_gpio_0}] {/U0 }]/U0 ]]

# XDC: ipshared/xilinx.com/ila_v4_0/54adf773/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ila_adc_0 || ORIG_REF_NAME==system_ila_adc_0}]

# XDC: bd/system/ip/system_ila_adc_0/system_ila_adc_0_ooc.xdc

# XDC: bd/system/ip/system_wfifo_mem_0/system_wfifo_mem_0/system_wfifo_mem_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_wfifo_mem_0 || ORIG_REF_NAME==system_wfifo_mem_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_wfifo_mem_0/system_wfifo_mem_0/system_wfifo_mem_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_wfifo_mem_0 || ORIG_REF_NAME==system_wfifo_mem_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_wfifo_mem_0/system_wfifo_mem_0_ooc.xdc

# XDC: bd/system/ip/system_wfifo_mem_1/system_wfifo_mem_1/system_wfifo_mem_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_wfifo_mem_1 || ORIG_REF_NAME==system_wfifo_mem_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_wfifo_mem_1/system_wfifo_mem_1/system_wfifo_mem_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_wfifo_mem_1 || ORIG_REF_NAME==system_wfifo_mem_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_wfifo_mem_1/system_wfifo_mem_1_ooc.xdc

# XDC: bd/system/ip/system_wfifo_mem_2/system_wfifo_mem_2/system_wfifo_mem_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_wfifo_mem_2 || ORIG_REF_NAME==system_wfifo_mem_2}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_wfifo_mem_2/system_wfifo_mem_2/system_wfifo_mem_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_wfifo_mem_2 || ORIG_REF_NAME==system_wfifo_mem_2}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_wfifo_mem_2/system_wfifo_mem_2_ooc.xdc

# XDC: bd/system/ip/system_wfifo_mem_3/system_wfifo_mem_3/system_wfifo_mem_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_wfifo_mem_3 || ORIG_REF_NAME==system_wfifo_mem_3}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_wfifo_mem_3/system_wfifo_mem_3/system_wfifo_mem_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_wfifo_mem_3 || ORIG_REF_NAME==system_wfifo_mem_3}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_wfifo_mem_3/system_wfifo_mem_3_ooc.xdc

# XDC: bd/system/ip/system_rst_axi_ddr_cntrl_200M_0/system_rst_axi_ddr_cntrl_200M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_axi_ddr_cntrl_200M_0 || ORIG_REF_NAME==system_rst_axi_ddr_cntrl_200M_0}]

# XDC: bd/system/ip/system_rst_axi_ddr_cntrl_200M_0/system_rst_axi_ddr_cntrl_200M_0_ooc.xdc

# XDC: bd/system/ip/system_rst_axi_ddr_cntrl_200M_0/system_rst_axi_ddr_cntrl_200M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_axi_ddr_cntrl_200M_0 || ORIG_REF_NAME==system_rst_axi_ddr_cntrl_200M_0}]

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_s05_data_fifo_0/system_s05_data_fifo_0_ooc.xdc

# XDC: bd/system/ip/system_s06_data_fifo_0/system_s06_data_fifo_0_ooc.xdc

# XDC: bd/system/ip/system_s07_data_fifo_0/system_s07_data_fifo_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_s00_mmu_0/system_s00_mmu_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_0 || ORIG_REF_NAME==system_auto_us_cc_df_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_1 || ORIG_REF_NAME==system_auto_us_cc_df_1}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2_ooc.xdc

# XDC: bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_2 || ORIG_REF_NAME==system_auto_us_cc_df_2}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_cc_df_3/system_auto_us_cc_df_3_ooc.xdc

# XDC: bd/system/ip/system_auto_us_cc_df_3/system_auto_us_cc_df_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_3 || ORIG_REF_NAME==system_auto_us_cc_df_3}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_cc_df_4/system_auto_us_cc_df_4_ooc.xdc

# XDC: bd/system/ip/system_auto_us_cc_df_4/system_auto_us_cc_df_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_4 || ORIG_REF_NAME==system_auto_us_cc_df_4}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1/system_auto_cc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1/system_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1 || ORIG_REF_NAME==system_auto_cc_1}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_2/system_auto_cc_2_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_2/system_auto_cc_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_2 || ORIG_REF_NAME==system_auto_cc_2}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_0 || ORIG_REF_NAME==system_auto_us_df_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_1 || ORIG_REF_NAME==system_auto_us_df_1}] {/inst }]/inst ]]

# XDC: bd/system/system_ooc.xdc

# XDC: C:/Projetos_git/repo_analog/hdl/projects/fmcomms2/kc705/system_constr.xdc

# XDC: C:/Projetos_git/repo_analog/hdl/projects/common/kc705/kc705_system_constr.xdc
