# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {BD 41-1348}  -new_severity {INFO} 
set_msg_config  -id {BD 41-1343}  -new_severity {INFO} 
set_msg_config  -id {BD 41-1306}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-1687}  -new_severity {INFO} 
set_msg_config  -id {filemgmt 20-1763}  -new_severity {INFO} 
set_msg_config  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
create_project -in_memory -part xc7k325tffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths {
  C:/Projetos_git/repo_analog/hdl/library
  C:/Projetos_git/repo/vivado_projects/project_AES-IP
} [current_fileset]

add_files C:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_mb_0/system_sys_mb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_ilmb_cntlr_0/system_sys_ilmb_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_lmb_bram_0/system_sys_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_uart_0/system_axi_uart_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_uart_0/system_axi_uart_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_uart_0/system_axi_uart_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_timer_0/system_axi_timer_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_timer_0/system_axi_timer_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_gpio_sw_led_0/system_axi_gpio_sw_led_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_gpio_sw_led_0/system_axi_gpio_sw_led_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_gpio_sw_led_0/system_axi_gpio_sw_led_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_intc_0/system_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_intc_0/system_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_intc_0/system_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/ipshared/analog.com/axi_hdmi_tx_v1_0/008f4d65/axi_hdmi_tx_constr.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/ipshared/analog.com/axi_spdif_tx_v1_0/7e62f61d/axi_spdif_tx_constr.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_linear_flash_0/system_axi_linear_flash_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_linear_flash_0/system_axi_linear_flash_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_fmcomms2_spi_0/system_axi_fmcomms2_spi_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_fmcomms2_spi_0/system_axi_fmcomms2_spi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_fmcomms2_spi_0/system_axi_fmcomms2_spi_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_fmcomms2_spi_0/system_axi_fmcomms2_spi_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_fmcomms2_gpio_0/system_axi_fmcomms2_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_fmcomms2_gpio_0/system_axi_fmcomms2_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_axi_fmcomms2_gpio_0/system_axi_fmcomms2_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/ipshared/xilinx.com/ila_v4_0/54adf773/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_ila_adc_0/system_ila_adc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_0/system_wfifo_mem_0/system_wfifo_mem_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_0/system_wfifo_mem_0/system_wfifo_mem_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_0/system_wfifo_mem_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_1/system_wfifo_mem_1/system_wfifo_mem_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_1/system_wfifo_mem_1/system_wfifo_mem_1.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_1/system_wfifo_mem_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_2/system_wfifo_mem_2/system_wfifo_mem_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_2/system_wfifo_mem_2/system_wfifo_mem_2.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_2/system_wfifo_mem_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_3/system_wfifo_mem_3/system_wfifo_mem_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_3/system_wfifo_mem_3/system_wfifo_mem_3.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_wfifo_mem_3/system_wfifo_mem_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_rst_axi_ddr_cntrl_200M_0/system_rst_axi_ddr_cntrl_200M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_rst_axi_ddr_cntrl_200M_0/system_rst_axi_ddr_cntrl_200M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_rst_axi_ddr_cntrl_200M_0/system_rst_axi_ddr_cntrl_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_s05_data_fifo_0/system_s05_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_s06_data_fifo_0/system_s06_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_s07_data_fifo_0/system_s07_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_s00_mmu_0/system_s00_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_3/system_auto_us_cc_df_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_3/system_auto_us_cc_df_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_4/system_auto_us_cc_df_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_4/system_auto_us_cc_df_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_cc_1/system_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_cc_1/system_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_cc_2/system_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_cc_2/system_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/system_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib {
  C:/Projetos_git/repo_analog/hdl/library/common/ad_iobuf.v
  C:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.srcs/sources_1/imports/hdl/system_wrapper.v
  C:/Projetos_git/repo_analog/hdl/projects/fmcomms2/kc705/system_top.v
}
read_xdc C:/Projetos_git/repo_analog/hdl/projects/fmcomms2/kc705/system_constr.xdc
set_property used_in_implementation false [get_files C:/Projetos_git/repo_analog/hdl/projects/fmcomms2/kc705/system_constr.xdc]

read_xdc C:/Projetos_git/repo_analog/hdl/projects/common/kc705/kc705_system_constr.xdc
set_property used_in_implementation false [get_files C:/Projetos_git/repo_analog/hdl/projects/common/kc705/kc705_system_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Projetos_git/repo/vivado_projects/project_Analog-AES/fmcomms2_kc705.cache/wt [current_project]
set_property parent.project_dir C:/Projetos_git/repo/vivado_projects/project_Analog-AES [current_project]
catch { write_hwdef -file system_top.hwdef }
synth_design -top system_top -part xc7k325tffg900-2
write_checkpoint system_top.dcp
report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb
