# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/mb_subsystem/mb_subsystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem || ORIG_REF_NAME==mb_subsystem}]

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_v10_0 || ORIG_REF_NAME==mb_subsystem_dlmb_v10_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/mb_subsystem_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_v10_0 || ORIG_REF_NAME==mb_subsystem_ilmb_v10_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_0/mb_subsystem_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_lmb_bram_0/mb_subsystem_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_lmb_bram_0 || ORIG_REF_NAME==mb_subsystem_lmb_bram_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_periph_0/mb_subsystem_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_periph_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_xlconcat_0/mb_subsystem_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_xlconcat_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mdm_1_0 || ORIG_REF_NAME==mb_subsystem_mdm_1_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_rst_mig_7series_0_100M_0/mb_subsystem_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==mb_subsystem_rst_mig_7series_0_100M_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_timer_0_0 || ORIG_REF_NAME==mb_subsystem_axi_timer_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_0/mb_subsystem_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mb_subsystem_axi_bram_ctrl_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_mem_intercon_0/mb_subsystem_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_mem_intercon_0 || ORIG_REF_NAME==mb_subsystem_axi_mem_intercon_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xbar_0 || ORIG_REF_NAME==mb_subsystem_xbar_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_xbar_1/mb_subsystem_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xbar_1 || ORIG_REF_NAME==mb_subsystem_xbar_1}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_bram_0/mb_subsystem_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==mb_subsystem_axi_bram_ctrl_0_bram_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_AES_AXI_0_0/mb_subsystem_AES_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_AES_AXI_0_0 || ORIG_REF_NAME==mb_subsystem_AES_AXI_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_0/mb_subsystem_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_0_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_0_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/constraints/mb_subsystem_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/constraints/mb_subsystem_mig_7series_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_v10_0 || ORIG_REF_NAME==mb_subsystem_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/mb_subsystem_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_v10_0 || ORIG_REF_NAME==mb_subsystem_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/mb_subsystem_ilmb_v10_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_0/mb_subsystem_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_lmb_bram_0/mb_subsystem_lmb_bram_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_mdm_1_0 || ORIG_REF_NAME==mb_subsystem_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_rst_mig_7series_0_100M_0/mb_subsystem_rst_mig_7series_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==mb_subsystem_rst_mig_7series_0_100M_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_rst_mig_7series_0_100M_0/mb_subsystem_rst_mig_7series_0_100M_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_rst_mig_7series_0_100M_0/mb_subsystem_rst_mig_7series_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==mb_subsystem_rst_mig_7series_0_100M_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_timer_0_0 || ORIG_REF_NAME==mb_subsystem_axi_timer_0_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_0/mb_subsystem_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_xbar_1/mb_subsystem_xbar_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_bram_0/mb_subsystem_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_0/mb_subsystem_clk_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_0_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_0/mb_subsystem_clk_wiz_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_0/mb_subsystem_clk_wiz_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_0_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/mb_subsystem_ooc.xdc
