# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param simulator.modelsimInstallPath C:/questasim64_10.2c/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:kc705:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths {{c:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs}} [current_fileset]
read_vhdl -library xil_defaultlib {
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/project_TCC_v1.srcs/sources_1/new/Mux_2x1.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/project_TCC_v1.srcs/sources_1/new/Mux_10x1.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/new/DeMux_1x2.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/new/Control_Decryption.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/new/Control.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/new/Clock_div32.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/project_TCC_v1.srcs/sources_1/new/SubBytes.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/project_TCC_v1.srcs/sources_1/new/ShiftRows.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/project_TCC_v1.srcs/sources_1/new/MixColumns.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/project_TCC_v1.srcs/sources_1/new/KeyExpansion.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/project_TCC_v1.srcs/sources_1/new/InvSubBytes.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/project_TCC_v1.srcs/sources_1/new/InvShiftRows.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/project_TCC_v1.srcs/sources_1/new/InvMixColumns.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/project_TCC_v1.srcs/sources_1/new/AddKey.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/hdl/myip_lite_v1_0_S00_AXI.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/new/AES_Crypto.vhd}
  {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.srcs/sources_1/imports/sources_1/imports/hdl/myip_lite_v1_0.vhd}
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP/project_AES-IP.cache/wt} [current_project]
set_property parent.project_dir {C:/Users/Janier Arias Garcia/Documents/Projeto_Caio/project_AES-IP} [current_project]
synth_design -top myip_lite_v1_0 -part xc7k325tffg900-2
write_checkpoint myip_lite_v1_0.dcp
report_utilization -file myip_lite_v1_0_utilization_synth.rpt -pb myip_lite_v1_0_utilization_synth.pb
